version: "3"
services:
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - ./frontend/.env
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
  terraform:
    image: hashicorp/terraform:1.2.3
    volumes:
      - ./terraform:/terraform
    env_file: ./terraform/.env
    working_dir: /terraform
    entrypoint: ash
    tty: true