version: "3"
services:
  terraform:
    image: hashicorp/terraform:1.2.3
    volumes:
      - ./terraform:/terraform
    env_file: ./terraform/.env
    working_dir: /terraform
    entrypoint: ash
    tty: true