version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
executors:
  default:
    docker:
      - image: cimg/node:16.15-browsers
      - image: cimg/python:3.6
    working_directory: ~/repo
commands:
  npm_install:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "./frontend/react-app/package.json" }}
            - v2-dependencies-
      - run:
          working_directroy: frontend/react-app
          command: cd frontend/react-app && npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "./frontend/react-app/package.json" }}
jobs:
  build:
    executor: default
    steps:
      - checkout
      - npm_install
      - run:
          command: npm install python3 && cd ./frontend/react-app && npm run build
      - persist_to_workspace:
          root: frontend/react-app
          paths:
            - "*"
            - ".*"
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/repo/frontend/react-app
      - aws-s3/sync:
          from: build
          to: s3://web.ymnk.fun
          overwrite: true
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build