version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && cd bucket && git clone git@github.com:mountaincenter/aws_terraform_circleci.git
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: aws_terraform_circleci
          to: 's3://web.ymnk.fun'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: aws_terraform_circleci
          to: 's3://web.ymnk.fun'
workflows:
  s3-example:
    jobs:
      - build
