version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          arguments: |
            --acl public-read \
            --acl bucket-owner-full-control \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./index.html
          to: 's3://web.ymnk.fun'
workflows:
  s3-example:
    jobs:
      - build:
          filters:
            branches:
              only: main
