version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && cd bucket && git clone -b development git@github.com:mountaincenter/aws_terraform_circleci.git
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --acl bucket-owner-full-control \
            --cache-control "max-age=86400" \
            --delete
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: bucket/aws_terraform_circlceci
          to: 's3://web.ymnk.fun/prefix'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/aws_terraform_circleci/index.html
          to: 's3://web.ymnk.fun'
workflows:
  s3-example:
    jobs:
      - build
